services:

  mysql:
    build: 
      dockerfile: Dockerfile.mysql
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_mhs
      MYSQL_PASSWORD: db_mhs
      MYSQL_USER: db_mhs
    ports:
      - "3306:3306"
    networks:
      - react_crud
    volumes:
      - mysql:/var/lib/mysql
      - ./data.sql:/docker-entrypoint-initdb.d/data.sql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  server:
    build: 
      dockerfile: Dockerfile.server
    depends_on:
      - mysql
    ports:
      - 5500:5500
    networks:
      - react_crud
  
  frontend:
    build: 
      dockerfile: Dockerfile.frontend
    depends_on:
      - mysql
      - server
    ports:
      - 3000:3000
    networks:
      - react_crud

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    environment:
      PMA_HOST: mysql
      PMA_USER: db_mhs
      PMA_PASSWORD: db_mhs
    depends_on:
      - mysql
    ports:
      - 8080:80
    networks:
      - react_crud

networks:
  react_crud:

volumes:
  mysql: